### ISSUE TITLE
OSError: the function is only available for the windows platform

### ISSUE THREAD

**Issue by whodanyalahmed** [Delgan/win32-setctime#5]
OSError: the function is only available for the windows platform....

I have a MAC OS and this doesnt work on my laptop xan you please help me out how can i use this in mac? Or same functionality by other Library for MAC?

**Comment by Delgan** [comment]
Hi.

This library is intended for Windows only. I don't know how this could be implemented for macOS, maybe check out this StackOverflow question: [How to change the creation date of file using python on a mac?](https://stackoverflow.com/questions/56008797/how-to-change-the-creation-date-of-file-using-python-on-a-mac).
