### ISSUE TITLE
Don't follow symbolic links

### ISSUE THREAD

**Issue by 1024mb** [Delgan/win32-setctime#6]
Could an option to ignore symlinks be added? Currently it follows the symlink and the actual file gets updated.

**Comment by Delgan** [comment]
Hi.

That sounds like a good idea. I added a new `follow_symlinks` argument (defaults to `True`) to the `setctime()`function.

You can uprade to `1.1.0` to use it. 👍

**Comment by 1024mb** [comment]
@Delgan I just tried it and it works great. Can you please make a module for mtime and atime? I'm asking because `os.utime` doesn't support `follow_symlinks` on Windows and your module does.

**Comment by Delgan** [comment]
The documentation of [`os.utime()`](https://docs.python.org/3/library/os.html#os.utime) states you can use `follow_symlinks=False`. Are you saying this parameter does not work on Windows?

**Comment by 1024mb** [comment]
Yes, I've tried it and it doesn't work, you will get something along the lines that `follow_symlinks` is not supported on this platform. Even querying `os.utime in os.supports_follow_symlinks` returns `False`.

**Comment by Delgan** [comment]
Ok, thanks. I didn't know the support for symlinks was platform dependent, there even exists [`os.supports_follow_symlinks`](https://docs.python.org/3/library/os.html#os.supports_follow_symlinks) to list supported functions.

I'm sorry but I prefer not to add the `utime()` support to this library. It wouldn't fit its name, it was only meant to change the `st_ctime` attribute and my usage does not require modifying the other ones.

Ideally, support for symlinks should be added directly to the official Python implementation. I looked at the code a bit, and after finding the implementation I opened a feature request: https://bugs.python.org/issue46490

Maybe the `os.utime()` function will be improved.

**Comment by 1024mb** [comment]
>I'm sorry but I prefer not to add the utime() support to this library. 

I was not referring to add support to setctime but to create another module.
Either way, hopefully support it's added in next versions of Python. Thanks for opening the issue.
